# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install

      - run:
          name: install linters
          command: |
            sudo apt-get install curl
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install nodejs
            sudo npm install -g markdownlint-cli

      - run:
          name: lint markdown
          command: |
            markdownlint *.md

      - run:
          name: lint python
          command: |
            pipenv run pylint --rcfile=integrate/.pylintrc integrate

      - run:
          name: run tests
          command: |
            cd integrate/test
            export PYTHONPATH=/home/circleci/repo/integrate
            pipenv run python test_repocompiler.py
            pipenv run python test_mdcontentcheck.py
            pipenv run python SamplesFunctionalTest.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
